sudo: required
services:
  - docker

before_install:
  - docker build -t rajatchauhan407/react-docker -f Dockerfile.dev .

script:
  - docker run -e CI=true rajatchauhan407/react-docker npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-745411510829"
  bucket_path: "docker"
  on:
   branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
