sudo: required
services:
  - docker

before_install:
  - docker build -t rajatchauhan407/react-docker -f Dockerfile.dev .

script:
  - docker run -e CI=true rajatchauhan407/react-docker npm run test -- --coverage
