version: '3'
services: 
  react-docker:
    image: rajatchauhan407/react-check
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
  # tests:
  #   image: rajatchauhan407/react-check
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - /app/node_modules
  #     - .:/app
  #   command: npm run test